language: node_js
node_js: "7"
install: npm i
script: 
 - yarn run test
 - yarn run lint
 - yarn run flow
 - yarn run build

notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  repo: 'gerardburns/gerardburns.github.io'
  local_dir: build
  on:
    branch: master
